ci: use gitflow approach

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -1,15 +1,11 @@
-name: Tests
+name: Build and Test
+run-name: Build docker container and test
 
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - main
-    tags:
-      - 'v*.*.*'
   pull_request:
     branches:
-      - main
+      - "*"
 
 jobs:
   build:
@@ -29,17 +25,25 @@ jobs:
           python-version: ${{ matrix.python-version }}
       - name: Install dependencies
         run: |
-          pip install .[dev]
+          python3 -m venv venv
+          source venv/bin/activate
+          python3 -m pip install .[dev]
       - name: Validate commits
         if: github.ref != 'refs/heads/main'
         run: |
+          source venv/bin/activate
           cz check --rev-range origin/main..
       - name: Test with pytest
         run: |
+          source venv/bin/activate
           pytest
   nf-test:
     runs-on: self-hosted # Uses https://github.com/GlobalPathogenAnalysisService/git_runners
     steps:
+      - name: clean up # nf-test needs to sudo to remove, so will fail automatic cleanup
+        run: |
+          sudo rm -rf .nf-test || true
+
       - uses: actions/checkout@v4
         with:
           token: "${{ secrets.PAT_TOKEN }}"
@@ -53,3 +57,8 @@ jobs:
 
       - name: Run nf-test
         run: nf-test test tests/workflow.nf.test --profile local_docker
+
+      - name: clean up 2
+        if: always()
+        run: |
+          sudo rm -rf .nf-test || true
